# Generated by Django 3.2.12 on 2022-06-13 04:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220610_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identification_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
