# Generated by Django 3.2.12 on 2022-06-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_identification_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identification_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
