# Generated by Django 3.2.9 on 2022-07-30 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('descrption', models.TextField(blank=True, max_length=500, null=True)),
                ('price', models.IntegerField(default=0)),
                ('photo', models.ImageField(upload_to='')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'ordering': ['created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
    ]
